// Add new employee

export const ADD_NEW_EMPLOYEE_REQUEST = 'ADD_NEW_EMPLOYEE_REQUEST'
export const ADD_NEW_EMPLOYEE_SUCCESS ='ADD_NEW_EMPLOYEE_SUCCESS'
export const ADD_NEW_EMPLOYEE_FAILED ='ADD_NEW_EMPLOYEE_FAILED'

// remove employee

export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST'
export const REMOVE_EMPLOYEE_SUCCESS ='REMOVE_EMPLOYEE_SUCCESS'
export const REMOVE_EMPLOYEE_FAILED ='REMOVE_EMPLOYEE_FAILED'


//Modify employee

export const MODIFY_EMPLOYEE_REQUEST = 'MODIFY_EMPLOYEE_REQUEST'
export const MODIFY_EMPLOYEE_SUCCESS ='MODIFY_EMPLOYEE_SUCCESS'
export const MODIFY_EMPLOYEE_FAILED ='MODIFY_EMPLOYEE_FAILED'

// get employee

export const  GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST'
export const GET_EMPLOYEE_SUCCESS ='GET_EMPLOYEE_SUCCESS'
export const GET_EMPLOYEE_FAILED ='GET_EMPLOYEE_FAILED'

// edit employee

export const  EDIT_EMPLOYEE_REQUEST = 'EDIT_EMPLOYEE_REQUEST'
export const EDIT_EMPLOYEE_SUCCESS ='EDIT_EMPLOYEE_SUCCESS'
export const EDIT_EMPLOYEE_FAILED ='EDIT_EMPLOYEE_FAILED'


// Image upload

export const  IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS ='IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAILED ='IMAGE_UPLOAD_FAILED'



// delete upload

export const  REMOVE_UPLOAD_REQUEST = 'REMOVE_UPLOAD_REQUEST'
export const REMOVE_UPLOAD_SUCCESS ='REMOVE_UPLOAD_SUCCESS'
export const REMOVE_UPLOAD_FAILED ='REMOVE_UPLOAD_FAILED'


// get upload

export const  GET_UPLOAD_REQUEST = 'GET_UPLOAD_REQUEST'
export const GET_UPLOAD_SUCCESS ='GET_UPLOAD_SUCCESS'
export const GET_UPLOAD_FAILED ='GET_UPLOAD_FAILED'

